### PR TITLE
Update links and content to new CodiMD repository

### LINKED ISSUE #20: Update links and content to new CodiMD repository
Since we moved to an [own organization](https://github.com/codimd) now, it would be great to update the links in the README.

Most of the links in the lower part point to the old repository and should be replaced. If you wonder about the background of this whole change, there is [a vision](https://github.com/codimd/server/issues/10) for the future that tries to explains how things went and what we plan to do in the future :slightly_smiling_face:

Also since most of those issues have no equivalent in the new repository, feel free to create new issues for them :+1: Time to get things rolling!

### PR DESCRIPTION
**Pull request by Fumesover**
fix #20

### CODE REVIEW

**Comment by pirate** [comment]
thx

**Comment by pirate** [comment]
@SISheogorath looks like I no longer have permission to merge PRs, so feel free to merge this whenever you want.

**Comment by SISheogorath** [comment]
:o that wasn't planned, @pirate! You should got an invitation that gives you access to the organization.

**Comment by pirate** [comment]
Ah, unfortunately joining the org requires 2FA, which I can't enable due to how I have my dotfile scripts set up.  (I promise I'm using a strong, random Github password managed by a password manager though)

**Comment by SISheogorath** [comment]
Just because it's you! :wink:

**Pull request merged**
